[package]
name = "ollie/tycoon-framework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Sessions = "2jammers/profilestore@0.1.0"
Promise = "evaera/promise@4.0.0"